version: '3.4'

services:

  web:
    image: nginx:latest
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html

  php:
    image: php:7.2-fpm
    working_dir: /var/www/html
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - .:/var/www/html

  db:
    image: mysql:5.7
    volumes:
      - ./docker/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tellitus
      - MYSQL_USER=tellitus
      - MYSQL_PASSWORD=0T4s0U2u

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: 0T4s0U2u
      MYSQL_PASSWORD: 0T4s0U2u
      MYSQL_ROOT_PASSWORD: root
