<?php

namespace App\Observers;

use App\Laravue\Models\Places;
use App\Laravue\Models\User;

class UserObserver
{
    /**
     * Handle the user "created" event.
     *
     * @param  \App\Laravue\Models\User  $user
     * @return void
     */
    public function created(User $user)
    {
        $place = new Places();
        $place->users_id = $user->id;
        $place->name = 'Default';
        $place->comment = 'Default place generated by system';
        $place->save();
    }

    /**
     * Handle the user "updated" event.
     *
     * @param  \App\Laravue\Models\User  $user
     * @return void
     */
    public function updated(User $user)
    {
    }

    /**
     * Handle the user "deleted" event.
     *
     * @param  \App\Laravue\Models\User  $user
     * @return void
     */
    public function deleted(User $user)
    {
        //
    }

    /**
     * Handle the user "restored" event.
     *
     * @param  \App\Laravue\Models\User  $user
     * @return void
     */
    public function restored(User $user)
    {
        //
    }

    /**
     * Handle the user "force deleted" event.
     *
     * @param  \App\Laravue\Models\User  $user
     * @return void
     */
    public function forceDeleted(User $user)
    {
        //
    }
}
